version: '2.4'
services:
  dataturks-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dataturks-db-vol:/var/lib/mysql
      - ./custom_mysql_scripts/:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqlshow --password=$$MYSQL_ROOT_PASSWORD 2> /dev/null | grep -q hope"
      timeout: 20s
      retries: 10

  dataturks-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      dataturks-db:
        condition: service_healthy
    expose:
      - '3000-3001'
      - '3030'
      - '9090'
    ports:
      - '80:80'
    volumes:
      - dataturks-app-vol:/home/dataturks/dataturks-fe/uploads
      - ./custom_onprem.yml:/home/dataturks/dataturks-be/onprem.yml
    healthcheck:
      test: "curl -s -o /dev/null -w '%{http_code}' http://localhost:9090/dtAPI | grep 404"
      timeout: 20s
      retries: 10

volumes:
  dataturks-db-vol:
  dataturks-app-vol:
